apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: revenueassurance
  namespace: tme-aix
spec:
  params:
    - default: 'https://github.com/fenar/TME-AIX.git'
      description: Repo URL
      name: GIT_URL
      type: string
    - default: 3.11-ubi9
      name: PYTHON_IMAGE
      type: string
    - default: 'https://ds-pipeline-dspa.tme-aix.svc.cluster.local:8443'
      name: KUBEFLOW_ENDPOINT
      type: string
    - default: 'http://minio.minio.svc.cluster.local:9000'
      name: S3_ENDPOINT
      type: string
    - default: T09QInleq4mA_Z4P
      name: AWS_ACCESS_KEY_ID
      type: string
    - default: DrkayJjcyGtnT_cybQBWm605gMMOY4mO
      name: AWS_SECRET_ACCESS_KEY
      type: string
    - default: pipeline-artifacts
      name: BUCKET_NAME
      type: string
    - default: 'c40335e4-4349-4f76-bc0a-b738e4864fbf'
      name: KUBEFLOW_PIPELINE_ID
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.GIT_URL)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: gitInitImage
          value: 'registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:868966ef9d4b54952d8a74eb83bba40eb1f52c0148994fa704efd0e3797c61c5'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: s2i-python
      params:
        - name: VERSION
          value: $(params.PYTHON_IMAGE)
        - name: PATH_CONTEXT
          value: revenueassurance
        - name: IMAGE
          value: 'image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/environment'
      runAfter:
          - git-clone
      taskRef:
        kind: ClusterTask
        name: s2i-python
      workspaces:
        - name: source
          workspace: source
    - name: execute-kubeflow-pipeline
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/environment
        - name: TAG
          value: latest
        - name: SCRIPT
          value: 01-telco-revass-randomforest-pipeline.py
        - name: KUBEFLOW_ENDPOINT
          value: $(params.KUBEFLOW_ENDPOINT)
      runAfter:
        - s2i-python
      taskRef:
        kind: Task
        name: execute-kubeflow-pipeline
    - name: build-and-push-application
      params:
        - name: IMAGE
          value: 'image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/app:1-1.0'
        - name: BUILDER_IMAGE
          value: 'registry.redhat.io/rhel8/buildah@sha256:b48f410efa0ff8ab0db6ead420a5d8d866d64af846fece5efb185230d7ecf591'
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: $(workspaces.source.path)/revenueassurance/docker/containerfile-app
        - name: CONTEXT
          value: $(workspaces.source.path)/revenueassurance
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: '--build-arg NAMESPACE=$(context.pipelineRun.namespace)'
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
      runAfter:
        - build-and-push-oci-artifact
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: source
    - name: build-and-push-oci-artifact
      params:
        - name: IMAGE
          value: 'image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/model:1-1.0'
        - name: BUILDER_IMAGE
          value: 'registry.redhat.io/rhel8/buildah@sha256:b48f410efa0ff8ab0db6ead420a5d8d866d64af846fece5efb185230d7ecf591'
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: $(workspaces.source.path)/revenueassurance/docker/containerfile-oci-artifact
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: '--build-arg S3_ENDPOINT=$(params.S3_ENDPOINT) --build-arg AWS_ACCESS_KEY_ID=$(params.AWS_ACCESS_KEY_ID) --build-arg AWS_SECRET_ACCESS_KEY=$(params.AWS_SECRET_ACCESS_KEY) --build-arg BUCKET_NAME=$(params.BUCKET_NAME) --build-arg KUBEFLOW_PIPELINE_ID=$(params.KUBEFLOW_PIPELINE_ID) --build-arg TASK_NAME="train-model" --build-arg OUTPUT_FILE="model_file"'
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
      runAfter:
        - execute-kubeflow-pipeline
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: source
  workspaces:
    - name: source
