# Use the official Python image from the Docker Hub
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY docker/requirements.txt requirements.txt

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

ARG NAMESPACE

# Copy the current directory contents into the container at /app
COPY --from=image-registry.openshift-image-registry.svc:5000/$NAMESPACE/model:1-1.0 model.pkl model.pkl

# Expose port 35000 for Flask
EXPOSE 35000

# Copy the python app
COPY 01-randomforest-model_server.py app.py

# Command to run the Flask application
CMD ["python", "app.py"]
